import os
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv
from mood import MoodVector

load_dotenv()

SCOPE = "playlist-modify-public playlist-modify-private user-read-private"


def _make_auth(redirect_uri: str) -> SpotifyOAuth:
    return SpotifyOAuth(
        client_id=os.getenv("SPOTIFY_CLIENT_ID"),
        client_secret=os.getenv("SPOTIFY_CLIENT_SECRET"),
        redirect_uri=redirect_uri,
        scope=SCOPE,
        cache_path=".spotify_cache",
        open_browser=False,
    )


def get_auth_url(redirect_uri: str) -> str:
    return _make_auth(redirect_uri).get_authorize_url()


def get_spotify_from_code(code: str, redirect_uri: str) -> spotipy.Spotify:
    auth = _make_auth(redirect_uri)
    auth.get_access_token(code, as_dict=True, check_cache=False)
    return spotipy.Spotify(auth_manager=auth)


def get_spotify_client() -> spotipy.Spotify:
    """CLI use only (pipeline.py)."""
    return spotipy.Spotify(
        auth_manager=SpotifyOAuth(
            client_id=os.getenv("SPOTIFY_CLIENT_ID"),
            client_secret=os.getenv("SPOTIFY_CLIENT_SECRET"),
            redirect_uri=os.getenv("SPOTIFY_REDIRECT_URI", "http://127.0.0.1:8501"),
            scope=SCOPE,
            cache_path=".spotify_cache",
            open_browser=True,
        )
    )


def fetch_recommendations(sp: spotipy.Spotify, mood: MoodVector, limit: int = 20) -> list[str]:
    queries = mood.seed_genres + mood.search_terms + ["top hits"]
    seen: set[str] = set()
    track_uris: list[str] = []

    for query in queries:
        if len(track_uris) >= limit:
            break
        try:
            results = sp.search(q=query, type="track", limit=5)
            for track in (results.get("tracks", {}).get("items") or []):
                uri = track.get("uri", "")
                if uri.startswith("spotify:track:") and uri not in seen:
                    seen.add(uri)
                    track_uris.append(uri)
                if len(track_uris) >= limit:
                    break
        except spotipy.SpotifyException as e:
            if e.http_status == 401:
                raise
            continue

    return track_uris


def create_playlist(
    sp: spotipy.Spotify,
    track_uris: list[str],
    primary_hex: str,
    mood_description: str,
) -> str:
    playlist = sp._post(
        "me/playlists",
        payload={
            "name": f"{mood_description} — {primary_hex}",
            "public": True,
            "description": f"Generated by Synesthesia | Color: {primary_hex} | Mood: {mood_description}",
        },
    )
    playlist_id = playlist["id"]
    for i in range(0, len(track_uris), 100):
        sp.playlist_add_items(playlist_id, track_uris[i : i + 100])
    return playlist["external_urls"]["spotify"]
